name: R

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install gdal
        run: sudo apt install libgdal-dev
      - name: Install dependencies
        run: install.packages(c("testthat", "Rcpp", "RcppArmadillo", "terra"))
        shell: Rscript {0}
      - name: Tests
        run: testthat::test_file("tests.R", reporter = c("summary", "fail"))
        shell: Rscript {0}
